src/puzzles.js 
src/rewards.js 
src/utils/helpers.js 
src/constants.js 
src/generator/GroupTechnique.js 
src/generator/HoleTechnique.js 
src/generator/MazeTechnique.js 
src/generator/ScrewTechnique.js 
src/generator/SwitchTechnique.js 
src/generator/PuzzleGenerator.js 
src/generator/GeneratedPanel.js 
src/core/SVGFactory.js 
src/core/BaseElement.js 
src/core/BuildElement.js 
src/core/UIElement.js 
src/core/Panel.js 
src/core/RewardsManager.js 
src/core/PuzzleParser.js 
src/core/PuzzleEncoder.js 
src/core/Game.js 
src/core/gameManager.js 
src/app.js 
